# Generated by Django 5.2.4 on 2025-07-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mirror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('url', models.URLField(unique=True)),
                ('active', models.BooleanField(default=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(choices=[('vless', 'VLESS'), ('vmess', 'VMESS'), ('trojan', 'Trojan'), ('ss', 'Shadowsocks')], max_length=10)),
                ('raw_link', models.TextField()),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField()),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('last_ping_ms', models.IntegerField(blank=True, null=True)),
                ('last_speed_kbps', models.FloatField(blank=True, null=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('is_working', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('protocol', 'host', 'port', 'user_id')},
            },
        ),
    ]
